// <auto-generated />
using System;
using Altima.Broker.AspNet.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Altima.Broker.AspNet.Mvc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210502173822_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Altima.Broker.System.Account.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Rule")
                        .HasColumnType("int")
                        .HasColumnName("Rule");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Officedriver.Contratos.Core.Cooperados.Model.Cooperado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("Situacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Cooperado");
                });

            modelBuilder.Entity("Altima.Broker.System.Account.User", b =>
                {
                    b.OwnsOne("Altima.Broker.System.Type.Password", "Password", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Altima.Broker.System.Type.Username", "Username", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Password");

                    b.Navigation("Username");
                });

            modelBuilder.Entity("Officedriver.Contratos.Core.Cooperados.Model.Cooperado", b =>
                {
                    b.OwnsOne("Officedriver.Contratos.Core.Types.Cnh.Cnh", "Cnh", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Cnh.Numero", "Numero", b2 =>
                                {
                                    b2.Property<long>("CnhCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("CnhNumero");

                                    b2.HasKey("CnhCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("CnhCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Data", "Validade", b2 =>
                                {
                                    b2.Property<long>("CnhCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<DateTime>("Value")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("CnhValidade");

                                    b2.HasKey("CnhCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("CnhCooperadoId");
                                });

                            b1.Navigation("Numero");

                            b1.Navigation("Validade");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Conta.Conta", "Conta", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Conta.Agencia", "Agencia", b2 =>
                                {
                                    b2.Property<long>("ContaCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(5)
                                        .HasColumnType("nvarchar(5)")
                                        .HasColumnName("ContaAgencia");

                                    b2.HasKey("ContaCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("ContaCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Conta.Numero", "Numero", b2 =>
                                {
                                    b2.Property<long>("ContaCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("ContaNumero");

                                    b2.HasKey("ContaCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("ContaCooperadoId");
                                });

                            b1.Navigation("Agencia");

                            b1.Navigation("Numero");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("Cpf");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Data", "DataCadastro", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataCadastro");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Data", "DataDesligamento", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataDesligamento");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Data", "DataMatricula", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataMatricula");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Data", "Nascimento", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("Nascimento");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.EMail", "EMail", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("EMail");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Bairro", "Bairro", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("EnderecoBairro");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Cep", "Cep", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(9)
                                        .HasColumnType("nvarchar(9)")
                                        .HasColumnName("EnderecoCep");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Cidade", "Cidade", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("EnderecoCidade");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Complemento", "Complemento", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("EnderecoComplemento");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Estado", "Estado", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("EnderecoEstado");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Logradouro", "Logradouro", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("EnderecoLogradouro");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Endereco.Numero", "Numero", b2 =>
                                {
                                    b2.Property<long>("EnderecoCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("EnderecoNumero");

                                    b2.HasKey("EnderecoCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoCooperadoId");
                                });

                            b1.Navigation("Bairro");

                            b1.Navigation("Cep");

                            b1.Navigation("Cidade");

                            b1.Navigation("Complemento");

                            b1.Navigation("Estado");

                            b1.Navigation("Logradouro");

                            b1.Navigation("Numero");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Matricula", "Matricula", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Matricula");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Nome", "Nome", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Nome");

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Rg.Rg", "Rg", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Data", "Expedicao", b2 =>
                                {
                                    b2.Property<long>("RgCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<DateTime>("Value")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("RgExpedicao");

                                    b2.HasKey("RgCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("RgCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Rg.Numero", "Numero", b2 =>
                                {
                                    b2.Property<long>("RgCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("RgNumero");

                                    b2.HasKey("RgCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("RgCooperadoId");
                                });

                            b1.Navigation("Expedicao");

                            b1.Navigation("Numero");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Telefone", "Celular", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Ddd", "Ddd", b2 =>
                                {
                                    b2.Property<long>("TelefoneCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(2)
                                        .HasColumnType("nvarchar(2)")
                                        .HasColumnName("CelularDdd");

                                    b2.HasKey("TelefoneCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("TelefoneCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Numero", "Numero", b2 =>
                                {
                                    b2.Property<long>("TelefoneCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("CelularNumero");

                                    b2.HasKey("TelefoneCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("TelefoneCooperadoId");
                                });

                            b1.Navigation("Ddd");

                            b1.Navigation("Numero");
                        });

                    b.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId");

                            b1.ToTable("Cooperado");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Ddd", "Ddd", b2 =>
                                {
                                    b2.Property<long>("TelefoneCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(2)
                                        .HasColumnType("nvarchar(2)")
                                        .HasColumnName("TelefoneDdd");

                                    b2.HasKey("TelefoneCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("TelefoneCooperadoId");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Numero", "Numero", b2 =>
                                {
                                    b2.Property<long>("TelefoneCooperadoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("TelefoneNumero");

                                    b2.HasKey("TelefoneCooperadoId");

                                    b2.ToTable("Cooperado");

                                    b2.WithOwner()
                                        .HasForeignKey("TelefoneCooperadoId");
                                });

                            b1.Navigation("Ddd");

                            b1.Navigation("Numero");
                        });

                    b.OwnsMany("System.Collections.Generic.IEnumerable`1[[Officedriver.Contratos.Core.Types.Contato, Officedriver.Contratos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]", "Contatos", b1 =>
                        {
                            b1.Property<long>("CooperadoId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.HasKey("CooperadoId", "Id");

                            b1.ToTable("CooperadoContatos");

                            b1.WithOwner()
                                .HasForeignKey("CooperadoId");

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.EMail", "EMail", b2 =>
                                {
                                    b2.Property<long>("0, Culture=neutral, PublicKeyToken=null]]CooperadoId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("0, Culture=neutral, PublicKeyToken=null]]Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("EMail");

                                    b2.HasKey("0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "0, Culture=neutral, PublicKeyToken=null]]Id");

                                    b2.ToTable("CooperadoContatos");

                                    b2.WithOwner()
                                        .HasForeignKey("0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "0, Culture=neutral, PublicKeyToken=null]]Id");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Nome", "Nome", b2 =>
                                {
                                    b2.Property<long>("0, Culture=neutral, PublicKeyToken=null]]CooperadoId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("0, Culture=neutral, PublicKeyToken=null]]Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("Nome");

                                    b2.HasKey("0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "0, Culture=neutral, PublicKeyToken=null]]Id");

                                    b2.ToTable("CooperadoContatos");

                                    b2.WithOwner()
                                        .HasForeignKey("0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "0, Culture=neutral, PublicKeyToken=null]]Id");
                                });

                            b1.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Telefone", "Telefone", b2 =>
                                {
                                    b2.Property<long>("0, Culture=neutral, PublicKeyToken=null]]CooperadoId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("0, Culture=neutral, PublicKeyToken=null]]Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.HasKey("0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "0, Culture=neutral, PublicKeyToken=null]]Id");

                                    b2.ToTable("CooperadoContatos");

                                    b2.WithOwner()
                                        .HasForeignKey("0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "0, Culture=neutral, PublicKeyToken=null]]Id");

                                    b2.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Ddd", "Ddd", b3 =>
                                        {
                                            b3.Property<long>("Telefone0, Culture=neutral, PublicKeyToken=null]]CooperadoId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("Telefone0, Culture=neutral, PublicKeyToken=null]]Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<string>("Value")
                                                .HasMaxLength(2)
                                                .HasColumnType("nvarchar(2)")
                                                .HasColumnName("TelefoneDdd");

                                            b3.HasKey("Telefone0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "Telefone0, Culture=neutral, PublicKeyToken=null]]Id");

                                            b3.ToTable("CooperadoContatos");

                                            b3.WithOwner()
                                                .HasForeignKey("Telefone0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "Telefone0, Culture=neutral, PublicKeyToken=null]]Id");
                                        });

                                    b2.OwnsOne("Officedriver.Contratos.Core.Types.Telefone.Numero", "Numero", b3 =>
                                        {
                                            b3.Property<long>("Telefone0, Culture=neutral, PublicKeyToken=null]]CooperadoId")
                                                .HasColumnType("bigint");

                                            b3.Property<int>("Telefone0, Culture=neutral, PublicKeyToken=null]]Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .UseIdentityColumn();

                                            b3.Property<string>("Value")
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("TelefoneNumero");

                                            b3.HasKey("Telefone0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "Telefone0, Culture=neutral, PublicKeyToken=null]]Id");

                                            b3.ToTable("CooperadoContatos");

                                            b3.WithOwner()
                                                .HasForeignKey("Telefone0, Culture=neutral, PublicKeyToken=null]]CooperadoId", "Telefone0, Culture=neutral, PublicKeyToken=null]]Id");
                                        });

                                    b2.Navigation("Ddd");

                                    b2.Navigation("Numero");
                                });

                            b1.Navigation("EMail");

                            b1.Navigation("Nome");

                            b1.Navigation("Telefone");
                        });

                    b.Navigation("Celular");

                    b.Navigation("Cnh");

                    b.Navigation("Conta");

                    b.Navigation("Contatos");

                    b.Navigation("Cpf");

                    b.Navigation("DataCadastro");

                    b.Navigation("DataDesligamento");

                    b.Navigation("DataMatricula");

                    b.Navigation("EMail");

                    b.Navigation("Endereco");

                    b.Navigation("Matricula");

                    b.Navigation("Nascimento");

                    b.Navigation("Nome");

                    b.Navigation("Rg");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
